import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
export const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}});
export const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
export const secret=(n:string)=>Deno.env.get(n)||'';
export const keys=()=>['GEMINI_API_KEY','GEMINI_API_KEY_2','GEMINI_API_KEY_3','GEMINI_AI_KEY_1','GEMINI_AI_KEY_2','GEMINI_AI_KEY_3'].map(secret).filter(Boolean);
export async function geminiText(prompt:string,grounded=false){let last='';const models=[secret('GEMINI_MODEL')||'gemini-3.8-flash','gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash'].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const key of keys()){for(const model of models){for(const bearer of [false,true]){try{const url=grounded?'https://generativelanguage.googleapis.com/v1beta/interactions':`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const payload=grounded?{model,input:prompt,tools:[{type:'google_search'}]}:{contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.4}};const headers:any={'Content-Type':'application/json'};if(bearer)headers.Authorization=`Bearer ${key}`;else headers['x-goog-api-key']=key;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload)});const raw=await r.text();if(!r.ok){last=raw.slice(0,500);if((r.status===401||r.status===403)&&bearer)break;continue}const j=JSON.parse(raw);const a=grounded?(j.output_text||j.outputText||''):(j.candidates?.[0]?.content?.parts||[]).map((p:any)=>p.text||'').join('');if(a)return a;last='Empty Gemini response';break}catch(e){last=String(e)}}}}throw Error('Gemini unavailable: '+last)}
export function b64bytes(v:string){return Uint8Array.from(atob(v.replace(/^data:[^,]+,/,'').replace(/\s/g,'')),c=>c.charCodeAt(0))}
export function findAudio(body:any){const out:any[]=[];const walk=(o:any)=>{if(!o)return;if(Array.isArray(o))return o.forEach(walk);if(typeof o==='object'){if(o.audio_url?.url)out.push(o.audio_url.url);if(typeof o.url==='string'&&(o.url.startsWith('data:audio/')||o.url.startsWith('http')))out.push(o.url);if(typeof o.data==='string'&&o.data.length>1000)out.push(o.data);Object.values(o).forEach(walk)}};walk(body);return out[0]||''}
export async function uploadAsset(audio:Uint8Array,mime:string,kind:string){const d=db(),id=crypto.randomUUID(),path=`${kind}/${id}.${mime.includes('wav')?'wav':'mp3'}`;const {error}=await d.storage.from('generated-audio').upload(path,audio,{contentType:mime,upsert:false});if(error)throw error;const {data,error:se}=await d.storage.from('generated-audio').createSignedUrl(path,3600);if(se)throw se;return {id,path,url:data.signedUrl}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const {kind,item_id,asset_id,amount,customer}=await req.json();let amt=Number(amount); if(kind==='ringtone'){if(item_id){const {data:r}=await db().from('ringtones').select('id,price_inr,active').eq('id',item_id).single();if(!r||!r.active)throw Error('Ringtone unavailable');amt=Number(r.price_inr);if(amt<10)throw Error('Minimum ringtone payment is ₹10');}else if(asset_id){const {data:a}=await db().from('generated_assets').select('id,kind').eq('id',asset_id).single();if(!a||a.kind!=='ringtone')throw Error('Generated ringtone asset not found');amt=10;}else throw Error('Ringtone item is required');} if(kind==='song'){if(!asset_id)throw Error('Song asset is required');const {data:a}=await db().from('generated_assets').select('id').eq('id',asset_id).single();if(!a)throw Error('Song asset not found');amt=19;} if(kind==='design'){if(!asset_id)throw Error('Design asset is required');const {data:a}=await db().from('generated_assets').select('id').eq('id',asset_id).single();if(!a)throw Error('Design asset not found');amt=9;}if(kind==='tip'||kind==='gift')amt=Number(amount);if(!amt||(kind!=='design'&&amt<10))throw Error('Minimum payment is ₹10');const key=secret('RAZORPAY_KEY_ID'),sec=secret('RAZORPAY_KEY_SECRET');if(!key||!sec)throw Error('Razorpay keys are not configured in Supabase');const publicId='NAVA-'+crypto.randomUUID().slice(0,8).toUpperCase();const d=db();const {data:o,error}=await d.from('orders').insert({public_order_id:publicId,kind,item_id:item_id||null,asset_id:asset_id||null,amount_inr:amt,customer_email:customer?.email||null,customer_data:customer||{}}).select().single();if(error)throw error;const auth=btoa(`${key}:${sec}`);const r=await fetch('https://api.razorpay.com/v1/payment_links',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json'},body:JSON.stringify({amount:amt*100,currency:'INR',description:`NavaBharat AI ${kind} — ₹${amt}`,reference_id:publicId,callback_url:`${secret('SITE_URL')||'https://navabharatai.racharlgpt.in'}/?payment=done&order_id=${encodeURIComponent(publicId)}`,callback_method:'get',notes:{order_id:publicId}})});const j=await r.json();if(!r.ok)throw Error(j.error?.description||'Razorpay error');await d.from('orders').update({razorpay_link_id:j.id}).eq('id',o.id);return json({order_id:publicId,payment_link:j.short_url})}catch(e){return json({error:String(e.message||e)},500)}});
