import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
export const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}});
export const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
export const secret=(n:string)=>Deno.env.get(n)||'';
export const keys=()=>['GEMINI_API_KEY','GEMINI_API_KEY_2','GEMINI_API_KEY_3','GEMINI_AI_KEY_1','GEMINI_AI_KEY_2','GEMINI_AI_KEY_3'].map(secret).filter(Boolean);
export async function geminiText(prompt:string,grounded=false){let last='';const models=[secret('GEMINI_MODEL')||'gemini-3.8-flash','gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash'].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const key of keys()){for(const model of models){for(const bearer of [false,true]){try{const url=grounded?'https://generativelanguage.googleapis.com/v1beta/interactions':`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const payload=grounded?{model,input:prompt,tools:[{type:'google_search'}]}:{contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.4}};const headers:any={'Content-Type':'application/json'};if(bearer)headers.Authorization=`Bearer ${key}`;else headers['x-goog-api-key']=key;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload)});const raw=await r.text();if(!r.ok){last=raw.slice(0,500);if((r.status===401||r.status===403)&&bearer)break;continue}const j=JSON.parse(raw);const a=grounded?(j.output_text||j.outputText||''):(j.candidates?.[0]?.content?.parts||[]).map((p:any)=>p.text||'').join('');if(a)return a;last='Empty Gemini response';break}catch(e){last=String(e)}}}}throw Error('Gemini unavailable: '+last)}
export function b64bytes(v:string){return Uint8Array.from(atob(v.replace(/^data:[^,]+,/,'').replace(/\s/g,'')),c=>c.charCodeAt(0))}
export function findAudio(body:any){const out:any[]=[];const walk=(o:any)=>{if(!o)return;if(Array.isArray(o))return o.forEach(walk);if(typeof o==='object'){if(o.audio_url?.url)out.push(o.audio_url.url);if(typeof o.url==='string'&&(o.url.startsWith('data:audio/')||o.url.startsWith('http')))out.push(o.url);if(typeof o.data==='string'&&o.data.length>1000)out.push(o.data);Object.values(o).forEach(walk)}};walk(body);return out[0]||''}
export async function uploadAsset(audio:Uint8Array,mime:string,kind:string){const d=db(),id=crypto.randomUUID(),path=`${kind}/${id}.${mime.includes('wav')?'wav':'mp3'}`;const {error}=await d.storage.from('generated-audio').upload(path,audio,{contentType:mime,upsert:false});if(error)throw error;const {data,error:se}=await d.storage.from('generated-audio').createSignedUrl(path,3600);if(se)throw se;return {id,path,url:data.signedUrl}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const {order_id}=await req.json();const d=db();const {data:o}=await d.from('orders').select('*').eq('public_order_id',order_id).single();if(!o)throw Error('Order not found');const key=secret('RAZORPAY_KEY_ID'),sec=secret('RAZORPAY_KEY_SECRET');const auth=btoa(`${key}:${sec}`);if(o.razorpay_link_id){const r=await fetch('https://api.razorpay.com/v1/payment_links/'+o.razorpay_link_id,{headers:{Authorization:`Basic ${auth}`}});const j=await r.json();if(j.status==='paid'){const now=new Date();await d.from('orders').update({razorpay_status:'paid',razorpay_payment_id:j.payments?.[0]?.payment_id||null,paid_at:now.toISOString()}).eq('id',o.id);o.razorpay_status='paid';if(o.kind==='ringtone'||o.kind==='song'){const {data:existing}=await d.from('download_entitlements').select('id').eq('order_id',o.id).maybeSingle();if(!existing){await d.from('download_entitlements').insert({order_id:o.id,item_id:o.item_id||null,asset_id:o.asset_id||null,expires_at:new Date(now.getTime()+30*864e5).toISOString()})}}}}return json({paid:o.razorpay_status==='paid',order_id,kind:o.kind})}catch(e){return json({error:String(e.message||e)},500)}});
