/* NavaBharat AI independent ad marketplace. All free editing happens in the browser.
   Paid ads are verified and approved by the separate ad-market Supabase function. */
(function(){
'use strict';
let localImages=[],timer=null,slide=0,lastData=[],paidBooking=null,adTimers=[];
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:''}catch{return ''}};
const getC=()=>window.NAVA_CONFIG||{};
async function api(body,admin=false){const c=getC();if(!c.SUPABASE_URL||!c.SUPABASE_ANON_KEY)throw Error('Supabase is not configured.');const headers={'Content-Type':'application/json','apikey':c.SUPABASE_ANON_KEY};if(admin){const token=sessionStorage.getItem('nava_admin_token');if(!token)throw Error('Unlock Admin first.');headers['x-admin-token']=token;}
 const r=await fetch(c.SUPABASE_URL+'/functions/v1/ad-market',{method:'POST',headers,body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Advertisement service unavailable.');return j}
function notify(text){if(typeof window.toast==='function')window.toast(text);else alert(text)}
function price(f,p,d){if(f==='slideshow')return d===7?(p==='home'?199:99):(p==='home'?499:299);return d===7?(p==='home'?249:149):(p==='home'?599:399)}
async function jpg(file,max=960){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Only JPG, PNG, or WebP images are allowed.');const img=await createImageBitmap(file);try{const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let quality=.78,blob=null;for(let i=0;i<6;i++){blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',quality));if(blob&&blob.size<=340000)break;quality-=.11;}if(!blob||blob.size>340000)throw Error('Image too complex. Try a smaller photo.');return blob;}finally{img.close?.()}}
async function fileToBase64(blob){return await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result).split(',')[1]);f.onerror=()=>reject(Error('Image read failed'));f.readAsDataURL(blob)})}
function page(){return `<section class="hero"><h1>📢 NavaBharat Advertise & Slideshow Studio</h1><p>Make a business slideshow free in your browser. Businesses may optionally book clearly labeled sponsored slideshow or video placements. Every paid advertisement is reviewed before publication. If an ad cannot be approved, support will contact the advertiser about correction or any applicable refund.</p></section>
<div class="grid"><section class="card"><h3>🎞️ Free Business Slideshow Maker</h3><p class="muted">Choose up to six photos. No account, payment or Supabase upload is required to create and preview.</p><label>Business photos</label><input class="field" type="file" id="adFreePhotos" multiple accept="image/png,image/jpeg,image/webp" onchange="NavaAds.localPhotos()"><label>Business headline</label><input class="field" id="adFreeTitle" maxlength="80" placeholder="Your shop, product, course or service" oninput="NavaAds.localPreview()"><label>Seconds per slide</label><select class="field" id="adFreeSecs"><option value="3">3 seconds</option><option value="5" selected>5 seconds</option><option value="7">7 seconds</option></select><div id="adFreeOut" class="nava-ad-status"></div><div class="row"><button class="btn secondary" onclick="NavaAds.playLocal()">▶ Play slideshow</button><button class="btn secondary" onclick="NavaAds.downloadLocal()">⬇ Download HTML Slideshow</button></div><p class="muted">For an MP4 file, use the separate Video Studio Reel Maker. This free HTML slideshow runs locally and is not hosted by NavaBharat AI.</p></section>
<section class="card"><h3>💳 Book a Sponsored Placement</h3><div class="notice">Advertisements are optional and paid by the advertiser. All ordinary NavaBharat AI tools remain free where offered. No promised views, clicks or sales.</div><div class="nava-ad-fieldset"><label>Business or advertiser name<input id="adName" class="field" maxlength="90" placeholder="Business name"></label><label>Email for order correspondence<input id="adEmail" type="email" class="field" placeholder="business@example.com"></label><label>Advertisement headline<input id="adTitle" class="field" maxlength="90" placeholder="Special offer or service"></label><label>Short description<textarea id="adDescription" class="field" maxlength="420" placeholder="Explain your service without misleading claims"></textarea></label><label>Business website (HTTPS)<input id="adURL" type="url" class="field" placeholder="https://example.com"></label><label>Advertisement type<select id="adFormat" class="field" onchange="NavaAds.updatePrice()"><option value="slideshow">Photo slideshow</option><option value="video">Video advertisement</option></select></label><label>Video link (YouTube, Vimeo or direct MP4/WebM only)<input id="adVideoURL" type="url" class="field" placeholder="https://www.youtube.com/watch?v=..."></label><label>Placement<select id="adPlacement" class="field" onchange="NavaAds.updatePrice()"><option value="home">Home page</option><option value="search">Search</option><option value="jobs">Jobs & Exams</option><option value="creator">Creator Studio</option><option value="video">Video Studio</option></select></label><label>Duration<select id="adDays" class="field" onchange="NavaAds.updatePrice()"><option value="7">7 days</option><option value="30">30 days</option></select></label></div><p id="adPrice" class="price">₹199 / 7 days</p><label class="check"><input id="adRights" type="checkbox">I own or have permission to use all advertisement media, and agree to admin review before publication.</label><button class="btn" id="adPayBtn" onclick="NavaAds.book()">💳 Book with Razorpay</button><p class="muted">After verified payment, you can upload up to six compressed photos for a slideshow. Video ads use external links to save storage.</p><div id="adBookingStatus" class="nava-ad-status" role="status"></div></section></div>
<section class="card" style="margin-top:18px"><h3>🔍 Recover advertisement booking</h3><p class="muted">Keep both the Booking ID and private recovery code displayed after placing an order. These are different from existing music/ringtone order IDs.</p><div class="grid"><input id="adRecoverId" class="field" placeholder="Booking ID (AD-...)"><input id="adRecoverCode" class="field" placeholder="Private recovery code" type="password"></div><button class="btn secondary" onclick="NavaAds.recover()">Check booking / upload photos</button><div id="adRecoveryStatus" role="status"></div></section>
<section class="card" style="margin-top:18px"><h3>📺 Sponsored video & slideshow gallery</h3><p class="muted">Only verified, admin-approved advertisements are shown. Sponsored content is separate from official news and search results.</p><div id="adGallery" class="nava-ad-gallery"><div class="notice">Loading approved advertisements…</div></div></section>`}
function afterRender(page){
 for(const t of adTimers)clearInterval(t);adTimers=[];
 if(page==='advertise'){loadGallery();return}
 const placements=['home','search','jobs','creator','video'];if(!placements.includes(page))return;
 const content=$('#app .content');if(!content)return;
 const hero=content.querySelector('.hero')||content.firstElementChild;
 if(!hero)return;
 const titles={home:'Featured business promotions',search:'Sponsored in Search',jobs:'Sponsored in Jobs & Exams',creator:'Creator Studio sponsor',video:'Video Studio sponsor'};
 const slot=document.createElement('section');slot.className='card nava-sponsored-shell';
 slot.style.marginTop='18px';
 slot.innerHTML='<div class="slot-header"><div><span class="slot-badge">Sponsored</span><h3>'+escapeHTML(titles[page]||'Business advertisements')+'</h3></div><span class="nava-sponsored-note">Paid placements · Admin approved</span></div><div class="nava-sponsored-slot"><div class="nava-ads-grid" id="adSponsoredSlot"></div></div>';
 hero.insertAdjacentElement('afterend',slot);
 showAds(slot.querySelector('#adSponsoredSlot'),page,true).then(n=>{
  if(!n&&slot.isConnected){const target=slot.querySelector('#adSponsoredSlot');target.innerHTML='<div class="nava-slot-empty"><b>Promote your business on NavaBharat AI</b><p>Sponsored slideshow and click-to-play video placements are available after payment and approval.</p><button class="btn secondary" onclick="go(\'advertise\')">📢 View advertising options</button></div>'}
 }).catch(()=>{if(slot.isConnected)slot.querySelector('#adSponsoredSlot').innerHTML='<div class="muted">Sponsored placements are temporarily unavailable.</div>'});
}
async function loadGallery(){await showAds($('#adGallery'),null,false).catch(()=>{if($('#adGallery'))$('#adGallery').innerHTML='<div class="notice">Advertisement gallery is temporarily unavailable.</div>'})}
function vimeoEmbed(value){try{const u=new URL(value),h=u.hostname.replace(/^www\./,'');if(!['vimeo.com','player.vimeo.com'].includes(h))return '';const id=u.pathname.split('/').filter(Boolean).pop();return /^\d{5,15}$/.test(id||'')?'https://player.vimeo.com/video/'+id:''}catch{return ''}}
function youtubeEmbed(value){try{const u=new URL(value),host=u.hostname.replace(/^www\./,'');let id='';if(host==='youtu.be')id=u.pathname.slice(1);else if(host==='youtube.com'||host==='m.youtube.com'||host==='youtube-nocookie.com')id=u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||'';if(/^[A-Za-z0-9_-]{11}$/.test(id))return 'https://www.youtube-nocookie.com/embed/'+id;return ''}catch{return ''}}
async function showAds(target,placement,compact){if(!target)return 0;const result=await api({action:'public'});if(!target.isConnected)return 0;const ads=(result.ads||[]).filter(a=>!placement||a.placement===placement).slice(0,40);if(!ads.length){target.innerHTML=compact?'':'<div class="notice">No approved sponsored ads yet.</div>';return 0}
 target.innerHTML=ads.map((a,i)=>{const url=safeURL(a.destination_url),images=(a.images||[]).filter(safeURL),videoURL=safeURL(a.video_url),yt=youtubeEmbed(videoURL)||vimeoEmbed(videoURL);
 let media='';if(a.format==='video'&&yt)media=`<iframe loading="lazy" src="${escapeHTML(yt)}" title="Sponsored video" allow="accelerometer; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`;
 else if(a.format==='video'&&/\.(mp4|webm)(\?|$)/i.test(videoURL))media=`<video style="width:100%;max-height:260px" controls preload="none" src="${escapeHTML(videoURL)}"></video>`;
 else if(images.length)media=`<div class="nava-ad-slide"><img class="nava-ad-image" data-ad="${i}" src="${escapeHTML(images[0])}" alt="Sponsored business photo"></div>`;
 else media='<div class="nava-ad-slide"><span style="font-size:48px">📢</span></div>';
 return `<article class="card nava-ad-card"><div class="nava-sponsored">Sponsored · Advertisement</div><h3>${escapeHTML(a.title)}</h3>${media}<p>${escapeHTML(a.description)}</p><p class="muted">${escapeHTML(a.advertiser_name)}</p>${url?`<a class="btn secondary" href="${escapeHTML(url)}" target="_blank" rel="sponsored noopener noreferrer">Visit advertiser ↗</a>`:''}</article>`}).join('');
 ads.forEach((a,i)=>{const imgs=(a.images||[]).filter(safeURL);if(imgs.length>1){let at=0;const t=setInterval(()=>{const im=target.querySelector(`img[data-ad="${i}"]`);if(!im?.isConnected){clearInterval(t);return}at=(at+1)%imgs.length;im.src=imgs[at]},5000);adTimers.push(t)}});return ads.length}
async function localPhotos(){const files=[...($('#adFreePhotos')?.files||[])];if(files.length>6)return notify('Maximum six photos.');try{localImages=[];for(const file of files)localImages.push(await jpg(file));slide=0;localPreview()}catch(e){notify(e.message)}}
function localPreview(preserveTimer=false){const out=$('#adFreeOut');if(!out)return;if(!preserveTimer){clearInterval(timer);timer=null}if(!localImages.length){out.innerHTML='<p class="muted">Select photos to preview.</p>';return}
 const imgURL=URL.createObjectURL(localImages[slide]);if(out.dataset.url)URL.revokeObjectURL(out.dataset.url);out.dataset.url=imgURL;out.innerHTML=`<div class="nava-ad-slide"><img src="${imgURL}" alt="Your local slideshow image"><h3>${escapeHTML($('#adFreeTitle')?.value||'Your business')}</h3></div><p class="nava-ad-counter">Photo ${slide+1} / ${localImages.length} · stored only in this browser tab</p>`}
function playLocal(){if(!localImages.length)return notify('Choose business photos first.');clearInterval(timer);timer=setInterval(()=>{if(!$('#adFreeOut')){clearInterval(timer);timer=null;return}slide=(slide+1)%localImages.length;localPreviewWithoutStopping()},Math.max(3,Number($('#adFreeSecs')?.value||5))*1000);notify('Slideshow playing')}
function localPreviewWithoutStopping(){localPreview(true)}
async function downloadLocal(){if(!localImages.length)return notify('Choose photos first.');const data=[];for(const blob of localImages)data.push('data:image/jpeg;base64,'+await fileToBase64(blob));const title=String($('#adFreeTitle')?.value||'Business Slideshow');const slides=data.map(s=>`<img src="${s}" alt="Business photo">`).join('');const safeTitle=escapeHTML(title);const sec=Math.max(3,Number($('#adFreeSecs')?.value||5));const doc=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeTitle}</title><style>body{margin:0;background:#0c1021;color:white;text-align:center;font:18px system-ui}h1{margin:20px 12px}main{height:75vh;display:flex;align-items:center;justify-content:center}img{max-width:100%;max-height:100%;display:none;object-fit:contain}img.active{display:block}</style></head><body><h1>${safeTitle}</h1><main>${slides}</main><script>const a=[...document.querySelectorAll('img')];let i=0;function next(){a.forEach((e,n)=>e.classList.toggle('active',n===i));i=(i+1)%a.length}next();setInterval(next,${Math.round(sec*1000)})<\/script></body></html>`;
 const u=URL.createObjectURL(new Blob([doc],{type:'text/html'}));const a=document.createElement('a');a.href=u;a.download='navabharat-business-slideshow.html';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function updatePrice(){const f=$('#adFormat')?.value,p=$('#adPlacement')?.value,d=Number($('#adDays')?.value||7);if($('#adPrice'))$('#adPrice').textContent=`₹${price(f,p,d)} / ${d} days`}
function bookingMessage(text){const parent=$('#adBookingStatus');if(!parent)return;let box=parent.querySelector('#adBookingMessage');if(!box){box=document.createElement('div');box.id='adBookingMessage';box.className='notice';parent.prepend(box)}box.textContent=text}
function recoveryMessage(text){if($('#adRecoveryStatus'))$('#adRecoveryStatus').innerHTML='<div class="notice">'+escapeHTML(text)+'</div>'}
async function book(){const button=$('#adPayBtn');if(!$('#adRights')?.checked)return notify('Confirm your rights and advertiser terms.');if(typeof window.Razorpay!=='function')return notify('Razorpay checkout did not load. Refresh and try again.');if($('#adFormat')?.value==='slideshow'&&!$('#adFreePhotos')?.files?.length)return notify('Select slideshow photos in the free maker before booking.');
 if(button)button.disabled=true;try{const data={action:'create',format:$('#adFormat').value,placement:$('#adPlacement').value,days:Number($('#adDays').value),name:$('#adName').value,email:$('#adEmail').value,title:$('#adTitle').value,description:$('#adDescription').value,destination_url:$('#adURL').value,video_url:$('#adVideoURL').value};
 const order=await api(data);paidBooking={id:order.booking_id,code:order.recovery_code};
 if($('#adRecoverId'))$('#adRecoverId').value=order.booking_id;if($('#adRecoverCode'))$('#adRecoverCode').value=order.recovery_code;
 bookingMessage('Important: Save Booking ID '+order.booking_id+' and your private recovery code below before paying.');
 $('#adBookingStatus').insertAdjacentHTML('beforeend',`<div class="notice"><b>Booking ID:</b> <code>${escapeHTML(order.booking_id)}</code><br><b>Private recovery code:</b> <code style="overflow-wrap:anywhere">${escapeHTML(order.recovery_code)}</code><br><button class="btn secondary" onclick="NavaAds.copyBooking()">Copy booking details</button></div>`);
 const rz=new window.Razorpay({key:order.key_id,amount:order.amount,currency:'INR',name:'NavaBharat AI',description:'Sponsored ad booking',order_id:order.razorpay_order_id,handler:async resp=>{try{const v=await api({action:'verify',booking_id:order.booking_id,recovery_code:order.recovery_code,razorpay_order_id:resp.razorpay_order_id,razorpay_payment_id:resp.razorpay_payment_id,razorpay_signature:resp.razorpay_signature});if(v.paid){bookingMessage('Payment verified. Your advertisement is pending admin approval.');await uploadBookingImages();}else bookingMessage('Payment is pending. Recover it using your private booking code.')}catch(e){bookingMessage('Could not verify payment yet: '+e.message+'. Use Recover booking.')}},modal:{ondismiss:()=>bookingMessage('Checkout closed. Keep your Booking ID and private recovery code for recovery.')}});rz.on('payment.failed',r=>bookingMessage('Payment failed or canceled. You can recover the booking.'));rz.open();
 }catch(e){bookingMessage('Booking could not be created: '+e.message)}finally{if(button)button.disabled=false}}
function copyBooking(){if(!paidBooking)return;const t='NavaBharat AI Ad Booking\nBooking ID: '+paidBooking.id+'\nRecovery code: '+paidBooking.code;navigator.clipboard?.writeText(t).then(()=>notify('Booking details copied'),()=>notify('Copy manually from the booking panel'))}
async function uploadBookingImages(){if(!paidBooking)return;const files=[...($('#adFreePhotos')?.files||[])];if(!files.length){bookingMessage('Your ad is paid. For slideshow photos, choose images in the free maker and use Upload Paid Images.');const el=$('#adBookingStatus');if(el)el.insertAdjacentHTML('beforeend','<button class="btn secondary" onclick="NavaAds.uploadBookingImages()">⬆ Upload Paid Images</button>');return}
 if(files.length>6)return bookingMessage('Select no more than six photos.');
 try{for(let i=0;i<files.length;i++){bookingMessage(`Uploading sponsored photo ${i+1} of ${files.length}…`);const blob=await jpg(files[i]);await api({action:'upload',booking_id:paidBooking.id,recovery_code:paidBooking.code,mime:'image/jpeg',base64:await fileToBase64(blob)})}bookingMessage('Images uploaded. Waiting for admin approval.')}catch(e){bookingMessage('Photo upload failed: '+e.message+'. You can retry with the recovery code; contact support if uploads were partially completed.')}}
async function recover(){try{const id=$('#adRecoverId').value.trim(),code=$('#adRecoverCode').value.trim();const x=await api({action:'status',booking_id:id,recovery_code:code});paidBooking={id,code};recoveryMessage(`Booking: ${x.booking_id} · Payment: ${x.paid?'verified':'not completed'} · Status: ${x.status}`);if(x.paid&&['pending_review','rejected'].includes(x.status))$('#adRecoveryStatus').insertAdjacentHTML('beforeend','<button class="btn secondary" onclick="NavaAds.uploadBookingImages()">⬆ Upload slideshow photos selected above</button>')}catch(e){recoveryMessage(e.message)}}
function adminPanel(){return `<section class="card" style="margin-bottom:18px"><h3>📢 Advertisement Orders & Approvals</h3><p class="muted">Admin authorization is checked on the server. Approve only rights-cleared advertisements. Rejecting a paid ad requires manual refund handling where applicable.</p><button class="btn secondary" onclick="NavaAds.adminLoad()">Load Sponsored Bookings</button><div id="navaAdsAdmin" class="nava-ad-status"></div></section>`}
async function adminLoad(){
 const panel=$('#navaAdsAdmin');if(panel)panel.textContent='Loading campaigns…';
 try{
  const r=await api({action:'admin-list'},true);if(!panel)return;
  const header=`<div class="notice">Verified gross ad bookings: ₹${Number(r.gross_revenue_inr||0).toLocaleString('en-IN')} · Paid orders: ${r.paid_bookings} (before fees/refunds; not net profit)</div>`;
  const cards=(r.campaigns||[]).map(x=>{
   const id=escapeHTML(x.id),name=escapeHTML(x.title),status=escapeHTML(x.status),paid=escapeHTML(x.payment_status);
   let actions='';
   if(x.payment_status==='paid'){
    actions=`<button class="btn small" onclick="NavaAds.adminUpdate('${id}','active')">Approve / Activate</button><button class="btn small secondary" onclick="NavaAds.adminUpdate('${id}','paused')">Pause</button><button class="btn small secondary" onclick="NavaAds.adminUpdate('${id}','rejected')">Reject</button><button class="btn small secondary" onclick="NavaAds.adminDelete('${id}')">Clear expired media</button>`;
   }
   const link=safeURL(x.destination_url);const previews=(x.review_urls||[]).filter(safeURL).slice(0,6).map(u=>`<a target="_blank" rel="noopener noreferrer" href="${escapeHTML(u)}"><img alt="Review uploaded ad photo" style="width:84px;height:84px;object-fit:cover;margin:3px;border-radius:8px" src="${escapeHTML(u)}"></a>`).join('');const videoLink=safeURL(x.video_url);
   return `<div class="notice" style="margin-top:12px"><b>${name}</b> · ₹${Number(x.amount_inr)} · ${paid} · <b>${status}</b><br><small>${escapeHTML(x.public_id)} · ${escapeHTML(x.placement)} · ${escapeHTML(x.advertiser_name)} (${escapeHTML(x.email)}) · ${escapeHTML(x.format)} · ${x.images?.length||0} photos · ${escapeHTML(x.duration_days)} days</small><br><small>Expires: ${escapeHTML(x.ends_at||'Not active')}</small><div class="row">${previews}${videoLink?`<a target="_blank" rel="noopener noreferrer" href="${escapeHTML(videoLink)}">Review video ↗</a>`:''}</div><div class="row" style="margin-top:8px">${actions}<a href="${escapeHTML(link)}" target="_blank" rel="noopener noreferrer">Check link ↗</a></div></div>`;
  }).join('');panel.innerHTML=header+(cards||'<div class="notice">No bookings.</div>');
 }catch(e){if(panel)panel.textContent='Admin ads error: '+e.message}
}
async function adminUpdate(id,status){if(!confirm(`Change this campaign to ${status}? Paid rejections may require refund.`))return;try{await api({action:'admin-update',id,status},true);await adminLoad()}catch(e){notify(e.message)}}
async function adminDelete(id){if(!confirm('Remove campaign images? Active campaigns are protected. This cannot be undone.'))return;try{await api({action:'admin-delete-media',id},true);await adminLoad()}catch(e){notify(e.message)}}
window.NavaAds={page,afterRender,localPhotos,localPreview,playLocal,downloadLocal,book,updatePrice,recover,copyBooking,uploadBookingImages,adminPanel,adminLoad,adminUpdate,adminDelete};
})();
