import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
export const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}});
export const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
export const secret=(n:string)=>Deno.env.get(n)||'';
export const keys=()=>['GEMINI_API_KEY','GEMINI_API_KEY_2','GEMINI_API_KEY_3','GEMINI_AI_KEY_1','GEMINI_AI_KEY_2','GEMINI_AI_KEY_3'].map(secret).filter(Boolean);
export async function geminiText(prompt:string,grounded=false){let last='';const models=[secret('GEMINI_MODEL')||'gemini-3.8-flash','gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash'].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const key of keys()){for(const model of models){for(const bearer of [false,true]){try{const url=grounded?'https://generativelanguage.googleapis.com/v1beta/interactions':`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const payload=grounded?{model,input:prompt,tools:[{type:'google_search'}]}:{contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.4}};const headers:any={'Content-Type':'application/json'};if(bearer)headers.Authorization=`Bearer ${key}`;else headers['x-goog-api-key']=key;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload)});const raw=await r.text();if(!r.ok){last=raw.slice(0,500);if((r.status===401||r.status===403)&&bearer)break;continue}const j=JSON.parse(raw);const a=grounded?(j.output_text||j.outputText||''):(j.candidates?.[0]?.content?.parts||[]).map((p:any)=>p.text||'').join('');if(a)return a;last='Empty Gemini response';break}catch(e){last=String(e)}}}}throw Error('Gemini unavailable: '+last)}
export function b64bytes(v:string){return Uint8Array.from(atob(v.replace(/^data:[^,]+,/,'').replace(/\s/g,'')),c=>c.charCodeAt(0))}
export function findAudio(body:any){const out:any[]=[];const walk=(o:any)=>{if(!o)return;if(Array.isArray(o))return o.forEach(walk);if(typeof o==='object'){if(o.audio_url?.url)out.push(o.audio_url.url);if(typeof o.url==='string'&&(o.url.startsWith('data:audio/')||o.url.startsWith('http')))out.push(o.url);if(typeof o.data==='string'&&o.data.length>1000)out.push(o.data);Object.values(o).forEach(walk)}};walk(body);return out[0]||''}
export async function uploadAsset(audio:Uint8Array,mime:string,kind:string){const d=db(),id=crypto.randomUUID(),path=`${kind}/${id}.${mime.includes('wav')?'wav':'mp3'}`;const {error}=await d.storage.from('generated-audio').upload(path,audio,{contentType:mime,upsert:false});if(error)throw error;const {data,error:se}=await d.storage.from('generated-audio').createSignedUrl(path,3600);if(se)throw se;return {id,path,url:data.signedUrl}}

async function ace(lyrics:string,style:string,lang:string,duration:number,vocal:string){const key=secret('ACESTEP_API_KEY')||secret('ACE_API_KEY')||secret('ACE_APP_KEY');if(!key)throw Error('ACE key not configured');const base='https://api.acemusic.ai';const body={model:'acemusic/acestep-v1.5-turbo',messages:[{role:'user',content:`<prompt>Create a complete original ${style} audio piece. Use ${vocal}. Perform the supplied original idea/lyrics naturally in ${lang}. Polished beginning and ending.</prompt>\n<lyrics>${lyrics}</lyrics>`}],audio_config:{format:'mp3',vocal_language:lang,instrumental:vocal==='Instrumental',duration},use_cot_caption:false};const r=await fetch(base+'/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('ACE HTTP '+r.status+': '+(await r.text()).slice(0,400));const u=findAudio(await r.json());if(!u)throw Error('ACE returned no audio');if(u.startsWith('http')){const a=await fetch(u);return {bytes:new Uint8Array(await a.arrayBuffer()),mime:a.headers.get('content-type')||'audio/mpeg'}}return {bytes:Uint8Array.from(atob(u.split(',').pop()!),c=>c.charCodeAt(0)),mime:u.includes('wav')?'audio/wav':'audio/mpeg'}}
async function lyria(lyrics:string,style:string,lang:string,duration:number,vocal:string){let last='';for(const key of keys()){try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({model:secret('GEMINI_MUSIC_MODEL')||'lyria-3.5',input:`Create an original finished song in ${lang}. Style: ${style}. Vocal arrangement: ${vocal}. Approx ${duration}s. Original user idea/lyrics:\n${lyrics}`,response_format:{type:'audio'}})});const j=await r.json();if(!r.ok){last=JSON.stringify(j).slice(0,500);continue}const b=j.output_audio?.data||j.outputAudio?.data||j.output?.find?.((x:any)=>x.type==='audio')?.data;if(b)return {bytes:Uint8Array.from(atob(b),c=>c.charCodeAt(0)),mime:j.output_audio?.mime_type||'audio/mpeg'};last='No audio'}catch(e){last=String(e)}}throw Error('Gemini Lyria failed: '+last)}
async function apiFrame(lyrics:string,style:string,vocal:string){const key=secret('APIFRAME_API_KEY');if(!key)throw Error('APIFrame key not configured');const base='https://api.apiframe.ai/v2';const p:any={custom_mode:true,instrumental:vocal==='Instrumental',style,title:'NavaBharat AI Song'};const r=await fetch(base+'/music/generate',{method:'POST',headers:{'X-API-Key':key,'Content-Type':'application/json'},body:JSON.stringify({model:'suno',prompt:lyrics.slice(0,3000),sunoParams:p})});if(!r.ok)throw Error('APIFrame HTTP '+r.status);const j=await r.json();const id=j.id||j.job_id||j.jobId||j.task_id;if(!id)throw Error('APIFrame no job id');for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,5000));const q=await fetch(base+'/jobs/'+id,{headers:{'X-API-Key':key}});if(!q.ok)continue;const b=await q.json();const u=b.audioUrl||b.audio_url||b.audio;if(u){const a=await fetch(u);return {bytes:new Uint8Array(await a.arrayBuffer()),mime:'audio/mpeg'}}if(['failed','error','cancelled'].includes(String(b.status||b.state).toLowerCase()))break}throw Error('APIFrame generation timed out')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const {kind,lyrics,language,style,duration=15,vocal_type='Instrumental',admin_test=false,test_provider=''}=await req.json();if(admin_test){const token=req.headers.get('x-admin-token')||'';if(!token||token!==secret('ADMIN_API_TOKEN'))throw Error('Unauthorized')}const providers=(admin_test&&test_provider?[test_provider]:(secret('MUSIC_PROVIDER_ORDER')||'acestep,gemini,apiframe').split(',').map(x=>x.trim()));let audio:any=null,last='',used='';for(const p of providers){try{audio=p==='acestep'?await ace(lyrics,style,language,Math.min(Number(duration),60),vocal_type):p==='gemini'?await lyria(lyrics,style,language,Math.min(Number(duration),60),vocal_type):await apiFrame(lyrics,style,vocal_type);if(audio){used=p;break}}catch(e){last=String(e)}}if(!audio)throw Error('All music providers failed. '+last);const up=await uploadAsset(audio.bytes,audio.mime,kind==='ringtone'?'ringtones-generated':'songs');const client=db();const {data,error}=await client.from('generated_assets').insert({id:up.id,kind,storage_path:up.path,preview_path:up.path,provider:used,metadata:{language,style,duration}}).select().single();if(error)throw error;return json({asset_id:data.id,preview_url:up.url,provider:data.provider})}catch(e){return json({error:String(e.message||e)},500)}});
